### ISSUE TITLE
panic after connection time out

### ISSUE THREAD

**Issue by harenber** [harenber/ptc-go#29]
```
pi@funkpi:~/go/src/github.com/la5nta/pat $ ./pat connect "pactor:///HB9MM"
2020/05/10 15:37:18 Connecting to HB9MM (pactor)...
panic: runtime error: slice bounds out of range [2:0]

goroutine 9 [running]:
github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc.(*Modem).getChannelsStatus(0x1516140, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1313, 0x1)
	/home/pi/go/src/github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc/modem.go:612 +0x334
github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc.(*Modem).updatePactorState(0x1516140, 0x0, 0x0)
	/home/pi/go/src/github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc/modem.go:465 +0x24
github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc.(*Modem).statusThread(0x1516140)
	/home/pi/go/src/github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc/modem.go:255 +0x38
created by github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc.(*Modem).runControlLoops
	/home/pi/go/src/github.com/la5nta/pat/vendor/github.com/harenber/ptc-go/ptc/modem.go:238 +0x48
```

**Comment by harenber** [comment]
Seems the internal 100ms wait time is too small. With 200ms it never appeared again in my tests. Nevertheless, a code should never panic, wrote a check for that. Waiting to be checked in...
